#!/bin/bash
printf "This script will show you ANSI colors in Buddy\n"
printf "We have 8 colors:\n"
printf "This is \033[30mBlack\n"
printf "This is \033[31mRed\n"
printf "This is \033[32mGreen\n"
printf "This is \033[33mYellow\n"
printf "This is \033[34mBlue\n"
printf "This is \033[35mMagenta\n"
printf "This is \033[36mCyan\n"
printf "This is \033[37mWhite\n"
printf "You can also use those colors in background\n"
printf "We have 8 colors:\n"
printf "This is \033[40mBlack bg\n"
printf "This is \033[41mRed bg\n"
printf "This is \033[42mGreen bg\n"
printf "This is \033[43mYellow bg\n"
printf "This is \033[44mBlue bg\n"
printf "This is \033[45mMagenta bg\n"
printf "This is \033[46mCyan bg\n"
printf "This is \033[47mWhite bg\n"
printf "We also have a support for ANSI decorations:\n"
printf "This is \033[1mBold\n"
printf "This is \033[3mItalic\n"
printf "This is \033[4mUnderline\n"
printf "This is \033[9mStrikethrough\n"
printf "This is \033[7mReversed\n"
printf "Logs can user many styles at the same time\n"
printf "This is \033[32;41;1;4m Green with blold and underline on red bg\n"
printf "\n\n\n"
printf "Here is and example tests output:\n"
cat logs.txt
